### ISSUE TITLE
Error with Home Assistant v2023.5

### ISSUE THREAD

**Issue by ShlomiPorush** [chilikla/yerushamayim#1]
This is the error 

```
Logger: homeassistant.components.sensor
Source: custom_components/yerushamayim/sensor.py:51
Integration: Sensor (documentation, issues)
First occurred: 00:25:58 (1 occurrences)
Last logged: 00:25:58

Error while setting up yerushamayim platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yerushamayim/sensor.py", line 51, in async_setup_platform
    site = RestData(hass, "GET", URL, "UTF-8", None, None, None, None, False)
TypeError: RestData.__init__() missing 1 required positional argument: 'ssl_cipher_list'

```

**Comment by chilikla** [comment]
Already fixed.
